In [4]:
import math

x = sum(k**2 * math.sin(0.1 * k**2) for k in range(-3, 5))

print(x)

33.40807559372164


In [5]:
import math

x = sum(sum(math.sqrt(j) * k**2 * math.sin(0.1 * (k-j)**2) for k in range(-3,5)) for j in range(1,4))

print(x)

56.67140841573445


In [7]:
import math

x = math.sqrt(3)
y = 0.3*x**2 + math.sqrt(x)
z = math.sqrt(math.e) + x - math.log(x) - math.log10(x)
v = math.sqrt(math.tanh(x*y*z))

print(v)

0.9999999977333676


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0,4,500)
y = np.tanh(x)

plt.plot(x,y)
plt.xlabel('x')
plt.ylabel('y = tanh(x)')
plt.grid(True)

plt.show()

In [2]:
import cmath
import numpy as np

x = 4+1j
y = 3j

z = np.array([x**y, x*y**2, cmath.exp(cmath.sqrt(x))])

print(np.square(z[0]) + np.square(z[1]) + np.square(z[2]))

(1264.3700624311566+674.9862653038576j)


In [5]:
import cmath
import numpy as np

x = 4+1j
y = 3j

z = np.array([x**y, x*y**2, cmath.exp(cmath.sqrt(x))])

m = np.abs(z)
p = np.angle(z)

print(f'Array m: {m}')
print(f'Array p: {p}')


Array m: [ 0.47953615 37.10795063  7.50319894]
Array p: [-2.03336529 -2.89661399  0.24809839]


In [6]:
import cmath
import numpy as np

x = np.array([1, 2, -3, 4, 8, 8, 2, 2, 4]).reshape(3,3)

y = x + np.transpose(x) + 

[[ 1  2 -3]
 [ 4  8  8]
 [ 2  2  4]]
